apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ansible-morning-test-namespace
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://github.com/joshuacanter/namespace-demo
    targetRevision: HEAD
    path: templates/namespace-config
    helm:
      valueFiles:
      - /clusters/configuration/dev/namespace-config/ansible-morning-test/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops