namespace: bifrost

#specifies the quota to be used for resources
quota:
  enabled: true
  requests:
    cpu: '1'
    memory: 1Gi
  limits:
    cpu: '2'
    memory: 2Gi
  pods: "10"
  persistentvolumeclaims: "20"
  resourcequotas: "1"
  services: "5"

  #specifies the limit ranges for the chart
limits:
  enabled: true
  default:
    memory: 512Mi
  defaultRequest:
    cpu: 100m
    memory: 256Mi
  type: Container