apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: namespace-config
  namespace: openshift-gitops
spec:
  generators:
  - list:
      elements:
      - filepath: /clusters/dev/namespace-config/air/values.yaml
        name: air
      - filepath: /clusters/dev/namespace-config/fire/values.yaml
        name: fire
      - filepath: /clusters/dev/namespace-config/water/values.yaml
        name: water
      - filepath: /clusters/dev/namespace-config/bifrost/values.yaml
        name: bifrost
      - filepath: clusters/dev/namespace-config//values.yaml
        name: ''
      - filepath: clusters/dev/namespace-config/py-test/values.yaml
        name: ' + namespace + '
      - filepath: clusters/dev/namespace-config/py-test/values.yaml
        name: ' + namespace + '
      - filepath: clusters/dev/namespace-config/py-test/values.yaml
        name: ' + namespace + '
      - filepath: clusters/dev/namespace-config/py-test/values.yaml
        name: ' + namespace + '
      - filepath: clusters/dev/namespace-config/py-test/values.yaml
        name: py-test
  template:
    metadata:
      name: '{{name}}-namespace-config'
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        repoURL: https://github.com/joshuacanter/namespace-demo
        targetRevision: HEAD
        path: templates/namespace-config
        helm:
          valueFiles:
          - '{{filepath}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: openshift-gitops
